services:
  db_dev:
    image: postgres:17
    container_name: myapp_db_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - db_dev_data:/var/lib/postgresql/data

  db_test:
    image: postgres:17
    container_name: myapp_db_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myusertest
      POSTGRES_PASSWORD: postgrestest
      POSTGRES_DB: myapp_test
    tmpfs:
      - /var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: myapp_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db_dev
      - db_test
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_dev_data:
