networks:
  shared_network: # Criamos uma rede para comunicação entre serviços
    name: my_shared_network
    driver: bridge

services:
  db:
    image: postgres:17
    container_name: myapp_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_network

  db_test:
    image: postgres:17
    container_name: myapp_db_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myusertest
      POSTGRES_PASSWORD: postgrestest
      POSTGRES_DB: myapp_test
    tmpfs:
      - /var/lib/postgresql/data # Prevents data persistence in tests

  app:
    build:
      context: .
    container_name: myapp_api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
