const list = `CREATE TABLE IF NOT EXISTS "lists" (
id SERIAL PRIMARY KEY ,
name VARCHAR(100) NOT NULL,
createdAt TIMESTAMP DEFAULT NOW(),
userId INTEGER NOT NULL,
FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE)`;

export default list;
