const task = `CREATE TABLE IF NOT EXISTS "tasks" (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
completed BOOLEAN DEFAULT FALSE,
endDate TIMESTAMP DEFAULT NULL,
comment TEXT DEFAULT NULL,
createdAt TIMESTAMP DEFAULT NOW(),
listId INTEGER NOT NULL,
FOREIGN KEY (listId) REFERENCES lists(id) ON DELETE CASCADE)`;

export default task;
