const task = `CREATE TABLE IF NOT EXISTS "tasks" (
id SERIAL PRIMARY KEY,
name_task VARCHAR(100) NOT NULL,
completed BOOLEAN DEFAULT FALSE,
due_date TIMESTAMP DEFAULT NULL,
comment TEXT DEFAULT NULL,
created_at TIMESTAMP DEFAULT NOW(),
list_id INTEGER NOT NULL,
FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE)`;

export default task;
